version: "3"
services:
  api:
    container_name: vapor-prod-container
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: api:prod
    environment:
      SLEEP_LENGTH: ${SLEEP_LENGTH}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 8080:8080
    networks:
      - vapor-net
    depends_on:
      - db
  db:
    container_name: postgres-container
    image: postgres:12.1-alpine
    ports:
      - 5432:5432
    environment:
      SLEEP_LENGTH: ${SLEEP_LENGTH}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - vapor-net
    restart: unless-stopped
  web:
    container_name: nginx-container
    build:
      context: containers/nginx
      dockerfile: Dockerfile
    image: web:prod
    ports:
      - 80:80
    volumes:
      - log-data:/var/log/nginx
    networks:
      - vapor-net
    restart: unless-stopped
    depends_on:
      - api
networks:
  vapor-net:
    driver: bridge
volumes:
  log-data:
  db-data:
